/*!
 * -------------------------------------------
 * Copyright (c) 2019, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     gtest_helper.h
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2019-04-15
 * \Brief    implement of gtest_helper.h
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */
#ifndef TEST_UTIL_GTEST_HELPER_H_
#define TEST_UTIL_GTEST_HELPER_H_

#include <string>
#include <unordered_map>

namespace horizon {
namespace leetcode {

extern std::unordered_map<std::string, std::string> MYTESTPARAM;
std::unordered_map<std::string, std::string> FilterOwnTestParam(int argc,
                                                                char **argv);

}  // namespace leetcode
}  // namespace horizon

#endif  // TEST_UTIL_GTEST_HELPER_H_
