/*!
 * -------------------------------------------
 * Copyright (c) 2020, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     test_283.cpp
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2020/1/3
 * \Brief    implement of test_283.cpp
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */
#include "gtest/gtest.h"
#include "hobotlog/hobotlog.hpp"
#include "leetcode/leetcode.h"
#include "leetcode/utils/printer.h"
namespace horizon {
namespace leetcode {
namespace test {
TEST(leetcode, test_283) {
  SetLogLevel(INFO);
  std::vector<int> arr({1, 2, 0, 0, 23, 34, 12, 0});
  moveZeroes(arr);
  Printer(arr);
}

}  // namespace test
}  // namespace leetcode
}  // namespace horizon
