/*!
 * -------------------------------------------
 * Copyright (c) 2019, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     test_438.cpp
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2019/12/31
 * \Brief    implement of test_438.cpp
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */
#include "gtest/gtest.h"
#include "hobotlog/hobotlog.hpp"
#include "leetcode/leetcode.h"

namespace horizon {
namespace leetcode {
namespace test {
TEST(leetcode, test_438) {
  SetLogLevel(INFO);
  auto indexes = findAnagrams("cbaebabacd", "abc");
  for (auto &index : indexes) {
    LOGI << "cbaebabacd  Anagrams = " << index;
  }
}

}  // namespace test
}  // namespace leetcode
}  // namespace horizon
