/*!
 * -------------------------------------------
 * Copyright (c) 2020, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     test_76.cpp
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2020/1/2
 * \Brief    implement of test_76.cpp
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */
#include "gtest/gtest.h"
#include "hobotlog/hobotlog.hpp"
#include "leetcode/leetcode.h"
namespace horizon {
namespace leetcode {
namespace test {
TEST(leetcode, test_76) {
  SetLogLevel(INFO);

}

}  // namespace test
}  // namespace leetcode
}  // namespace horizon
