/*!
 * -------------------------------------------
 * Copyright (c) 2019, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     test_3.cpp
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2019/12/30
 * \Brief    implement of test_3.cpp
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */
#include "gtest/gtest.h"
#include "hobotlog/hobotlog.hpp"
#include "leetcode/leetcode.h"

namespace horizon {
namespace leetcode {
namespace test {
TEST(leetcode, test_3) {
  SetLogLevel(INFO);
  auto longest_str_chars =
      horizon::leetcode::Solution::lengthOfLongestSubstring("tmmzuxt");
  LOGI << "\"tmmzuxt\" long substring = " << longest_str_chars;
}

}  // namespace test
}  // namespace leetcode
}  // namespace horizon
