/*!
 * -------------------------------------------
 * Copyright (c) 2020, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     454.4sum-ii.cpp
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2020/1/11
 * \Brief    implement of 454.4sum-ii.cpp
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */
/*!
 * @brief https://leetcode-cn.com/problems/4sum-ii/
 * Time: O(n) + klog(k), k = 256, n = s.size()
 * Space: O(n)+
 */
#include "cassert"
#include "leetcode/leetcode.h"
namespace horizon {
namespace leetcode {
namespace II {
int fourSumCount(vector<int>& A, vector<int>& B, vector<int>& C,
                 vector<int>& D) {
  assert(A.size() == B.size() && B.size() == C.size() && C.size() == D.size());
}
}  // namespace II
}  // namespace leetcode
}  // namespace horizon
