/*!
 * -------------------------------------------
 * Copyright (c) 2020, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     printer.h
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2020/1/3
 * \Brief    implement of printer.h
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */

#ifndef LEETCODE_INCLUDE_LEETCODE_UTILS_PRINTER_H_
#define LEETCODE_INCLUDE_LEETCODE_UTILS_PRINTER_H_
#include <iostream>
template <typename T>
void Printer(const T& container) {
  for (const auto& ele : container) {
    std::cout << ele << " ";
  }
  std::cout << std::endl;
}
#endif  // LEETCODE_INCLUDE_LEETCODE_UTILS_PRINTER_H_
