/*!
 * -------------------------------------------
 * Copyright (c) 2020, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     217.contains-duplicate.cpp
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2020/1/17
 * \Brief    implement of 217.contains-duplicate.cpp
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */
/*!
 * @brief https://leetcode-cn.com/problems/contains-duplicate/
 * Time: O(n)
 * Space: O(n)+
 */
#include "leetcode/leetcode.h"
namespace horizon {
namespace leetcode {
bool containsDuplicate(vector<int>& nums) {
  std::unordered_map<int, int> counter;
  for (const auto& num : nums) {
    ++counter[num];
    if (counter[num] > 1) {
      return true;
    }
  }
  return false;
}
}  // namespace leetcode
}  // namespace horizon
