/*!
 * -------------------------------------------
 * Copyright (c) 2020, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     447.number-of-boomerangs.cpp
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2020/1/13
 * \Brief    implement of 447.number-of-boomerangs.cpp
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */
/*!
 * @brief https://leetcode-cn.com/problems/number-of-boomerangs/
 * Time:
 * Space:
 */
#include "leetcode/leetcode.h"
namespace horizon {
namespace leetcode {
int numberOfBoomerangs(vector<vector<int>>& points) {}
}  // namespace leetcode
}  // namespace horizon
