/*!
 * -------------------------------------------
 * Copyright (c) 2020, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     209.cpp
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2020/1/9
 * \Brief    implement of 209.cpp
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */
/*!
 * @brief https://leetcode-cn.com/problems/minimum-size-subarray-sum/
 * Time: O(n)
 * Space: O(1)
 */
#include "leetcode/leetcode.h"
namespace horizon {
namespace leetcode {
int minSubArrayLen(int s, vector<int>& nums) {
  int i = 0, j = 0;
  int sum = 0;
  int minlen = INT32_MAX;
  // [i,j]为滑动窗, i,j为当前考察的元素
  while (j <= nums.size() && i < nums.size()) {
    if (sum < s) {
      if (j < nums.size()) {
        sum += nums[j++];
      } else {
        break;
      }
    } else {
      minlen = std::min((j - i), minlen);
      sum -= nums[i++];
    }
  }
  return minlen == INT32_MAX ? 0 : minlen;
}
}  // namespace leetcode
}  // namespace horizon
